name: Doxygen Documentation

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Generate Doxygen Documentation
    runs-on: ubuntu-latest
    container: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install doxygen
        shell: bash
        run: apt update && apt install -y doxygen git graphviz

      - name: Generate Documentation
        shell: bash
        run: doxygen

      - name: Make Latex Documentation
        shell: bash
        working-directory: ./doc/latex
        run: make

      - name: Move refman.pdf
        shell: bash
        run: mv ./doc/latex/refman.pdf ./doc/html/refman.pdf

      - name: Deploy Documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html