name: RunTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Run make debug
      shell: bash
      run: make debug

    - name: Run ctest
      working-directory: ./build
      shell: bash
      run: ctest
