name: RunTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Folder
      shell: bash
      run: mkdir build

    - name: Run CMake
      working-directory: ./build
      shell: bash
      run: cmake ..

    - name: Run Make
      working-directory: ./build
      shell: bash
      run: make

    - name: Test
      working-directory: ./build
      shell: bash
      run: ctest
