name: Run Tests

on: 
  - push
  - pull_request

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Run make debug
      run: make debug

    - name: Run ctest
      working-directory: ./debug
      run: ctest

  make-production:
    name: Make production
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Run make production
      run: make debug
